steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--network=cloudbuild',
        '-t',
        'us-central1-docker.pkg.dev/budget-497306/actual-server-repo/actual-server:${_TAG}',
        '-t',
        'us-central1-docker.pkg.dev/budget-497306/actual-server-repo/actual-server:latest',
        '-f',
        'sync-server.Dockerfile',
        '.',
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'actual-vanilla-service',
        '--image',
        'us-central1-docker.pkg.dev/budget-497306/actual-server-repo/actual-server:${_TAG}',
        '--region',
        'us-central1',
      ]

images:
  - 'us-central1-docker.pkg.dev/budget-497306/actual-server-repo/actual-server:${_TAG}'
  - 'us-central1-docker.pkg.dev/budget-497306/actual-server-repo/actual-server:latest'

substitutions:
  _TAG: 'latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
